### ISSUE TITLE
docs: Example for type: local for client_auth

### ISSUE THREAD

**Issue by b33rcity** [kevincoakley/ansible-role-postgres#6]
I'll be the first to admit that my own noobishness led me to this, but in the interest of sparing others in the same boat the frustration, I want to suggest editing the example in the README so that it shows both `host` and `local` types for `postgres_client_auth`:

```
        postgres_client_auth:
          -
            type: host
            method: md5
            database: all
            user: all
            address: "0.0.0.0/0"
          -
            type: local
            method: md5
            database: all
            user: all
            address:
```

What threw me was that I looked at a default `pg_hba.conf` and saw that for `local` types, an `address` parameter is not needed. So, I omitted that map from my vars file and wasted an hour trying to figure out why it wasn't working. (Ansible's error messages being generally cryptic is an issue to open at Ansible's repo... for probably the millionth time 😛 ). After doing what I should've done in the first place and reading your source more carefully, I realized the obvious answer of including the `address` map with an empty value.

This was after finding that the example syntax of `- type: host` seemed to not be working when I wanted multiple sequence elements, but this one may have been due to other issues. In any case, putting `type` on a new line after the `-` is working for multiple elements in the sequence.
